package modelo.entidades;

public enum Genero {
	DEPORTE, CULTURA, INGENIERIA, CIENCIAS_BASICAS, CIENCIAS_ECONOMICAS, OSCIO,
	LITERATURA, CIENCIAS_COMPUTACIONALES, CIENCIAS_SOCIALES, SALUD, 
	POLITICA, RELIGION, MISTERIO, CIENCIAS_EXACTAS, FILOSOFIA, ARTE, ARQUITECTUTA,
	EDUCACION, OCULTISMO, HISTORIA, GEOGRAFIA, OTROS;
}